before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: '{{ .Os }}-{{ .Arch }}'
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native

brews:
  - tap:
      owner: johnmanjiro13
      name: homebrew-tap
    description: lgotm is a command for generation LGTM image and generated image is copied to clipboard.
    homepage: https://github.com/johnmanjiro13/lgotm
    license: MIT
    test: system "#{bin}/lgotm version"
